services:
  auth-api:
    build: .
    env_file:
      - .env
    volumes:
      - jwt_keys_data:/app/keys
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app_network
      - traefik-public
    labels:
      traefik.enable: "true"

      traefik.http.routers.auth-api.rule: "Host(`${DOMAIN}`) && PathPrefix(`/auth-back`)"
      traefik.http.routers.auth-api.entrypoints: "web"
      traefik.http.routers.auth-api.middlewares: "auth-api-strip"

      traefik.http.routers.auth-api-secure.rule: "Host(`${DOMAIN}`) && PathPrefix(`/auth-back`)"
      traefik.http.routers.auth-api-secure.entrypoints: "websecure"
      traefik.http.routers.auth-api-secure.tls: "true"
      traefik.http.routers.auth-api-secure.tls.certresolver: "${TLS_RESOLVER:-letsencrypt}"
      traefik.http.routers.auth-api-secure.middlewares: "auth-api-strip"

      traefik.http.middlewares.auth-api-strip.stripprefix.prefixes: "/auth-back"
      traefik.http.services.auth-api.loadbalancer.server.port: "8000"

      logging: "alloy"
      service: "lyceum-auth-backend"
      environment: "production"

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
      - traefik-public
      - logging




volumes:
  postgres_data:
  jwt_keys_data:

networks:
  app_network:
    driver: bridge
  traefik-public:
    external: true
    name: traefik-public
  logging:
    external: true
    name: logging