from app.domain.enums.role import Role
from app.domain.enums.gender import Gender
from datetime import datetime
from typing import Optional
from uuid import UUID

from app.domain.entities.permissions_preset import PermissionsPreset
from app.domain.entities.user import User
from app.domain.enums.permission import PermissionType


class IUserRepository:
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_login(self, login: str) -> User | None: ...
    async def create(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> bool: ...
    async def list_(self, login: str | None = None,
                    first_name: str | None = None, middle_name: str | None = None,
                    last_name: str | None = None, full_name: str | None = None,
                    gender: Gender | None = None, roles: list[Role] | None = None,
                    permissions: list[PermissionType] | None = None,
                    grades: list[int] | None = None, letters: list[str] | None = None,
                    graduation_years: list[int] | None = None,
                    class_names: list[str] | None = None,
                    sort_by: str | None = None, order: str | None = None,
                    offset: int = 0, limit: int = 20) -> list[User]: ...
    async def count(self, login: str,
                    first_name: str | None = None, middle_name: str | None = None,
                    last_name: str | None = None, full_name: str | None = None,
                    gender: Gender | None = None, roles: list[Role] | None = None,
                    permissions: list[PermissionType] | None = None,
                    grades: list[int] | None = None, letters: list[str] | None = None,
                    graduation_years: list[int] | None = None,
                    class_names: list[str] | None = None) -> int: ...


class IRefreshTokenRepository:
    async def create(self, user_id: UUID, token: str, expires_at: datetime) -> None: ...
    async def get_by_token(self, token: str) -> tuple[UUID, bool] | None: ...
    async def revoke_by_token(self, token: str) -> bool: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...


class IPermissionsPresetRepository:
    async def get_by_id(self, preset_id: UUID) -> PermissionsPreset | None: ...
    async def get_by_name(self, name: str) -> PermissionsPreset | None: ...
    async def create(self, preset: PermissionsPreset) -> PermissionsPreset: ...
    async def update(self, preset: PermissionsPreset) -> PermissionsPreset: ...
    async def delete(self, preset_id: UUID) -> bool: ...
    async def list_(self, name: Optional[str] = None,
                    sort_by: Optional[str] = None, order: Optional[str] = None,
                    offset: int = 0, limit: int = 20) -> list[PermissionsPreset]: ...
    async def count(self, name: str | None = None) -> int: ...
