from datetime import datetime
from uuid import UUID

from app.domain.entities.user import User


class IUserRepository:
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_login(self, login: str) -> User | None: ...
    async def create(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> bool: ...
    async def list_(self, offset: int, limit: int) -> list[User]: ...
    async def count(self) -> int: ...


class IRefreshTokenRepository:
    async def create(self, user_id: UUID, token: str, expires_at: datetime) -> None: ...
    async def get_by_token(self, token: str) -> tuple[UUID, bool] | None: ...
    async def revoke_by_token(self, token: str) -> bool: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...
