"""Token model removed permissions removed pk and lives in dormitory added

Revision ID: c678374cf617
Revises: 00c739a834c0
Create Date: 2026-08-05 16:04:57.067628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c678374cf617'
down_revision: Union[str, Sequence[str], None] = '00c739a834c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions_presets')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.add_column('users', sa.Column('pk', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('lives_in_dormitory', sa.Boolean(), nullable=True))
    op.create_check_constraint('ck_grade', 'users', 'grade BETWEEN 8 AND 11')
    op.create_check_constraint('ck_letter', 'users', "letter ~ '^[А-Я]$'")
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'department')
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', postgresql.ARRAY(postgresql.ENUM('auth_users_create', 'auth_users_read', 'auth_users_update', 'auth_users_delete', 'auth_basic_permissions_write', 'auth_keys_revoke', 'auth_master_permissions_write', 'auth_super_permission_grant', 'auth_super_permission_revoke', 'technical_support_orders_create', 'technical_support_orders_set_department', 'technical_support_orders_get', 'technical_support_orders_set_status', 'technical_support_orders_set_worker', 'auth_permissions_presets_create', 'auth_permissions_presets_read', 'auth_permissions_presets_update', 'auth_permissions_presets_delete', 'spravki_orders_create', 'spravki_orders_get_my', 'spravki_orders_get', name='permissiontype')), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department', postgresql.ENUM('academic_department', 'olympiad_support_department', 'medical_station', 'educational_department', 'library', 'it_department', 'laboratory_of_tech_teaching_aids', 'competitive_selection_department', 'additional_education_department', 'dormitory', name='department'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('ck_letter', 'users', type_='check')
    op.drop_constraint('ck_grade', 'users', type_='check')
    op.drop_column('users', 'lives_in_dormitory')
    op.drop_column('users', 'pk')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('permissions_presets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.ARRAY(postgresql.ENUM('auth_users_create', 'auth_users_read', 'auth_users_update', 'auth_users_delete', 'auth_basic_permissions_write', 'auth_keys_revoke', 'auth_master_permissions_write', 'auth_super_permission_grant', 'auth_super_permission_revoke', 'technical_support_orders_create', 'technical_support_orders_set_department', 'technical_support_orders_get', 'technical_support_orders_set_status', 'technical_support_orders_set_worker', 'auth_permissions_presets_create', 'auth_permissions_presets_read', 'auth_permissions_presets_update', 'auth_permissions_presets_delete', 'spravki_orders_create', 'spravki_orders_get_my', 'spravki_orders_get', name='permissiontype')), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('permissions_presets_pkey'))
    )
    # ### end Alembic commands ###
