"""user sorting params

Revision ID: bad0fead8832
Revises: 73e1dbbe4a87
Create Date: 2026-05-10 12:10:35.370382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad0fead8832'
down_revision: Union[str, Sequence[str], None] = '73e1dbbe4a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('letter', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'letter')
    op.drop_column('users', 'grade')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
