"""PermissionsPresets added

Revision ID: 73e1dbbe4a87
Revises: f4b6ed773652
Create Date: 2026-05-08 21:06:00.979643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73e1dbbe4a87'
down_revision: Union[str, Sequence[str], None] = 'f4b6ed773652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ENUM_NAME = "permissiontype"

NEW_VALUES = (
    "auth_permissions_presets_create",
    "auth_permissions_presets_read",
    "auth_permissions_presets_update",
    "auth_permissions_presets_delete",
)
permission_enum = postgresql.ENUM(
    'auth_users_create',
    'auth_users_read',
    'auth_users_update',
    'auth_users_delete',
    'auth_permissions_presets_create',
    'auth_permissions_presets_read',
    'auth_permissions_presets_update',
    'auth_permissions_presets_delete',
    'auth_basic_permissions_write',
    'auth_keys_revoke',
    'auth_master_permissions_write',
    'auth_super_permission_grant',
    'auth_super_permission_revoke',
    'technical_support_orders_create',
    'technical_support_orders_set_department',
    'technical_support_orders_get',
    'technical_support_orders_set_status',
    'technical_support_orders_set_worker',
    name=ENUM_NAME,
    create_type=False
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    for value in NEW_VALUES:
        op.execute(
            f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS '{value}';"
        )
    op.create_table('permissions_presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(permission_enum), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('permissions_presets')
    op.execute(f"ALTER TYPE {ENUM_NAME} RENAME TO {ENUM_NAME}_old;")

    op.execute(
        f"""
        CREATE TYPE {ENUM_NAME} AS ENUM (
            'auth_users_create',
            'auth_users_read',
            'auth_users_update',
            'auth_users_delete',

            'auth_basic_permissions_write',
            'auth_keys_revoke',
            
            'auth_master_permissions_write',

            'auth_super_permission_grant',
            'auth_super_permission_revoke',

            'technical_support_orders_create',
            'technical_support_orders_set_department',
            'technical_support_orders_get',
            'technical_support_orders_set_status',
            'technical_support_orders_set_worker'
        );
        """
    )

    op.execute(
        f"""
            ALTER TABLE users
            ALTER COLUMN permissions
            TYPE {ENUM_NAME}[]
            USING permissions::text[]::{ENUM_NAME}[]
            """
    )

    op.execute(f"DROP TYPE {ENUM_NAME}_old;")
    # ### end Alembic commands ###

