"""empty message

Revision ID: f4b6ed773652
Revises: c45e837847b8
Create Date: 2026-05-04 21:06:05.239597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4b6ed773652'
down_revision: Union[str, Sequence[str], None] = 'c45e837847b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
permission_enum = postgresql.ENUM(
    'auth_users_create',
    'auth_users_read',
    'auth_users_update',
    'auth_users_delete',
    'auth_basic_permissions_write',
    'auth_keys_revoke',
    'auth_master_permissions_write',
    'auth_super_permission_grant',
    'auth_super_permission_revoke',
    'technical_support_orders_create',
    'technical_support_orders_set_department',
    'technical_support_orders_get',
    'technical_support_orders_set_status',
    'technical_support_orders_set_worker',
    name='permissiontype'
)


def upgrade() -> None:
    """Upgrade schema."""
    permission_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.Enum('admin', 'teacher', 'student', 'parent', 'staff', 'guest', 'graduate', name='role')), nullable=False))
    op.add_column('users', sa.Column('permissions', postgresql.ARRAY(permission_enum), nullable=True))
    op.drop_column('users', 'departments')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'teacher', 'student', 'staff', name='role'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('departments', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True))
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
