"""Parent role added department enum added

Revision ID: b720dac5dd90
Revises: c45e837847b8
Create Date: 2026-04-23 18:45:36.232045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.domain.enums import department

# revision identifiers, used by Alembic.
revision: str = 'b720dac5dd90'
down_revision: Union[str, Sequence[str], None] = 'c45e837847b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

position_enum = sa.Enum('chief', 'worker', name='position_enum')
department_enum = sa.Enum('academic_department', 'olympiad_support_department', 'medical_station', 'educational_department', 'library', 'it_department', 'laboratory_of_tech_teaching_aids', 'competitive_selection_department', 'additional_education_department', name='department')
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE role ADD VALUE 'parent'")
    op.add_column('users', sa.Column('department_position', position_enum, nullable=True))
    op.alter_column(
        'users',
        'departments',
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=255)),
        type_=postgresql.ARRAY(department_enum),
        existing_nullable=True,
        postgresql_using="departments::department[]"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # 1. rename old type
    op.execute("ALTER TYPE role RENAME TO role_old")

    # 2. create new type without 'parent'
    op.execute("""
        CREATE TYPE role AS ENUM ('admin', 'teacher', 'student', 'staff')
    """)

    # 3. alter column to new type
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role TYPE role
        USING role::text::role
    """)

    # 4. drop old type
    op.execute("DROP TYPE role_old")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'departments',
               existing_type=postgresql.ARRAY(department_enum),
               type_=postgresql.ARRAY(sa.VARCHAR(length=255)),
               existing_nullable=True)
    op.drop_column('users', 'department_position')
    # ### end Alembic commands ###
