"""parent_child relationship department_member relationship

Revision ID: 45c4d85a17ea
Revises: c678374cf617
Create Date: 2026-08-10 20:07:33.257630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45c4d85a17ea'
down_revision: Union[str, Sequence[str], None] = 'c678374cf617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    department_enum = postgresql.ENUM(
        'academic_department',
        'olympiad_support_department',
        'medical_station',
        'educational_department',
        'library',
        'it_department',
        'laboratory_of_tech_teaching_aids',
        'competitive_selection_department',
        'additional_education_department',
        'dormitory',
        name='department',
        create_type=False
    )
    department_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('department_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department', department_enum, nullable=False),
    sa.Column('role', sa.Enum('admin', 'worker', name='departmentmemberrole'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department', name='uq_user_department')
    )
    op.create_table('parent_child',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('parent_id != child_id', name='ck_prevent_self_parenting'),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.alter_column('users', 'lives_in_dormitory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lives_in_dormitory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('parent_child')
    op.drop_table('department_members')
    # ### end Alembic commands ###
