"""departments

Revision ID: c45e837847b8
Revises: 15916ceb391d
Create Date: 2026-04-09 16:29:40.836409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c45e837847b8'
down_revision: Union[str, Sequence[str], None] = '15916ceb391d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('departments', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'departments')
    # ### end Alembic commands ###
